// --- CONSTANTS ---
export const AMD_SYMBOL = '֏';
export const MIN_WAGE_15X = 1125000; // 15 x Minimum Wage (used for PKS cap)
export const PKS_STATE_MAX = 25000;

// --- TRANSLATIONS ---
export const translations = {
    en: {
        header: 'SALARY CALCULATOR',
        subheader: 'Calculate Income Tax, PKS, and Stamp Duty for Armenia',
        input_label_gross: 'Registered (Gross) Salary',
        input_label_net: 'Clean (Net) Salary',
        result_label_gross: 'Registered (Gross) Salary',
        result_label_net: 'Clean (Net) Salary',
        switch_to: 'Switch to',
        tax_options_header: 'Tax & Pension Options',
        it_benefit: 'IT Sector Tax Benefit (10% Income Tax)',
        pks_header: 'Mandatory Cumulative Pension System (PKS)',
        pks_no: 'No participation',
        pks_no_desc: '0% Contribution',
        pks_voluntary: 'Voluntary (Joined after 07/2018)',
        pks_voluntary_desc: '5% Employee contribution (max 56,250 ֏)',
        pks_mandatory: 'Mandatory / Pre-2018 Voluntary',
        pks_mandatory_desc: '10% Total contribution (State matched/capped)',
        results_header: 'Calculation Results',
        input_gross_display: 'Input Gross:',
        calculated_gross_display: 'Calculated Gross:',
        input_net_display: 'Input Net:',
        calculated_net_display: 'Calculated Net:',
        breakdown_header: 'Deductions Breakdown',
        income_tax: 'Income Tax',
        stamp_duty: 'Stamp Duty:',
        pks_employee: 'PKS Employee Contrib.:',
        pks_state: 'PKS State Match/Cont.:',
        pks_total: 'Total Monthly PKS Fund:',
        footer_note: 'Calculations are based on Armenian tax legislation effective from Jan 1, 2023.',
        lang_en: 'English',
        lang_am: 'Հայերեն',
        lang_ru: 'Русский',
    },
    am: {
        header: 'ԱՇԽԱՏԱՎԱՐՁԻ ՀԱՇՎԻՉ',
        subheader: 'Հաշվարկել Եկամտային Հարկը, Սոց վճարը և Դրոշմանիշային Վճարը',
        input_label_gross: 'Գրանցված (համախառն) աշխատավարձ',
        input_label_net: 'Մաքուր Աշատավարձ',
        result_label_gross: 'Գրանցված (համախառն) աշխատավարձ',
        result_label_net: 'Մաքուր աշխատավարձ',
        switch_to: 'Փոխել',
        tax_options_header: 'Հարկային և Կենսաթոշակային Պարամետրեր',
        it_benefit: 'ՏՏ Ոլորտի Հարկային Արտոնություն (10% Եկամտահարկ)',
        pks_header: 'Պարտադիր Կուտակային Կենսաթոշակային Համակարգ (ԿԿՀ)',
        pks_no: 'Չեմ մասնակցում',
        pks_no_desc: '0% վճար',
        pks_voluntary: 'Կամավոր (Միացել է 07/2018-ից հետո)',
        pks_voluntary_desc: '5% աշխատողի վճար (առավելագույնը 56,250 ֏)',
        pks_mandatory: 'Պարտադիր / Մինչև 2018թ. կամավոր',
        pks_mandatory_desc: '10% ընդհանուր վճար (Պետության համամասնական/սահմանափակ)',
        results_header: 'Հաշվարկի Արդյունքները',
        input_gross_display: 'Մուտքագրված Համախառն:',
        calculated_gross_display: 'Հաշվարկված Համախառն:',
        input_net_display: 'Մուտքագրված Մաքուր:',
        calculated_net_display: 'Հաշվարկված Մաքուր:',
        breakdown_header: 'Հարկային Պահումներ',
        income_tax: 'Եկամտահարկ',
        stamp_duty: 'Դրոշմանիշային Վճար:',
        pks_employee: 'ԿԿՀ Աշխատողի Վճար:',
        pks_state: 'ԿԿՀ Պետական Համամասնական/Վճար:',
        pks_total: 'ԿԿՀ Ամսական Ընդհանուր Ֆոնդ:',
        footer_note: 'Հաշվարկները հիմնված են 2023թ. հունվարի 1-ից գործող ՀՀ հարկային օրենսդրության վրա։',
        lang_en: 'English',
        lang_am: 'Հայերեն',
        lang_ru: 'Русский',
    },
    ru: {
        header: 'КАЛЬКУЛЯТОР ЗАРПЛАТЫ',
        subheader: 'Расчет Подоходного Налога, НПС и Гербового Сбора',
        input_label_gross: 'Регистрируемая (Валовая) Зарплата',
        input_label_net: 'Чистая (На Руки) Зарплата',
        result_label_gross: 'Регистрируемая (Валовая) Зарплата',
        result_label_net: 'Чистая (На Руки) Зарплата',
        switch_to: 'Переключить на',
        tax_options_header: 'Налоговые и Пенсионные Параметры',
        it_benefit: 'Налоговая Льгота ИТ Сектора (10% Подоходный Налог)',
        pks_header: 'Обязательная Накопительная Пенсионная Система (НПС)',
        pks_no: 'Без участия',
        pks_no_desc: '0% Взнос',
        pks_voluntary: 'Добровольное (Присоединился после 07/2018)',
        pks_voluntary_desc: '5% взнос работника (макс. 56,250 ֏)',
        pks_mandatory: 'Обязательное / Добровольное до 2018 г.',
        pks_mandatory_desc: '10% Общий взнос (С Гос. участием/ограничением)',
        results_header: 'Результаты Расчета',
        input_gross_display: 'Введенная Валовая:',
        calculated_gross_display: 'Рассчитанная Валовая:',
        input_net_display: 'Введенная Чистая:',
        calculated_net_display: 'Рассчитанная Чистая:',
        breakdown_header: 'Разбивка Вычетов',
        income_tax: 'Подоходный Налог',
        stamp_duty: 'Гербовый Сбор:',
        pks_employee: 'НПС Взнос Работника:',
        pks_state: 'НПС Государственное Соответствие/Взнос:',
        pks_total: 'Общий Ежемесячный Фонд НПС:',
        footer_note: 'Расчеты основаны на налоговом законодательстве РА, действующем с 1 января 2023 года.',
        lang_en: 'English',
        lang_am: 'Հայերեն',
        lang_ru: 'Русский',
    },
};
